package Thalassa.Configuration;

import java.util.HashMap;

// This class provides essential service data and variables.
public class Constants {

    public static final String SERVICE_NAME = "Thalassa";
    public static String CERTIFICATE, CERTIFICATE_PATH, CERTIFICATE_FILE_NAME, CERTIFICATE_PASSWORD, JWT_KEY;

    public static final HashMap<String, HashMap<String, String>> LOCALIZATION = new HashMap<>() {{
        put("el", new HashMap<>() {{
            put("aboutAttention", "ΠΡΟΣΟΧΗ: ΑΥΤΗ Η ΥΠΗΡΕΣΙΑ ΒΡΙΣΚΕΤΑΙ ΣΕ ΣΤΑΔΙΟ ΑΝΑΠΤΥΞΗΣ. ΜΕΧΡΙ ΝΑ ΟΛΟΚΛΗΡΩΘΕΙ, ΔΕΝ ΠΡΟΚΥΠΤΕΙ ΕΥΘΥΝΗ ΛΟΓΩ ΒΛΑΒΗΣ, ΑΠΩΛΕΙΑΣ ΔΕΔΟΜΕΝΩΝ Ή ΟΠΟΙΑΣΔΗΠΟΤΕ ΑΛΛΗΣ ΑΡΝΗΤΙΚΗΣ ΣΥΝΕΠΕΙΑΣ ΠΟΥ ΟΦΕΙΛΕΤΑΙ ΣΤΗ ΧΡΗΣΗ ΤΗΣ.");
            put("aboutExperimental", "Η «Θάλασσα» είναι μια πειραματική υπηρεσία web για τη ναυτιλία που βασίζεται στην τεχνολογία blockchain. Δείτε περισσότερες πληροφορίες <a href=\\\"https://github.com/jdouv/Thalassa\\\" target=\\\"_blank\\\">εδώ</a>.");
            put("aboutSubtitle", "Ηλεκτρονική υπηρεσία για τη ναυτιλία.");
            put("adminBlockchainIsEmpty", "Το blockchain της υπηρεσίας είναι κενό, συνεπώς περιττεύει ο έλεγχος εγκυρότητας.");
            put("adminBlockchainIsInvalid", "Για κάποιο λόγο, το blockchain της υπηρεσίας δεν είναι έγκυρο.");
            put("adminBlockchainIsValid", "Το blockchain της υπηρεσίας είναι έγκυρο.");
            put("adminBlockchainResultsCalculationMessage", "Στα παρακάτω μπλοκ, η αναμενόμενη τιμή κατατεμαχισμού είναι διαφορετική από αυτήν που βρέθηκε.");
            put("adminBlockchainResultsReferenceMessage", "Στα παρακάτω μπλοκ, η αναφορά του δεύτερου μπλοκ στην τιμή κατατεμαχισμού του πρώτου μπλοκ είναι διαφορετική από την πραγματική τιμή κατατεμαχισμού του πρώτου μπλοκ.");
            put("adminValidateBlockchain", "Έλεγχος εγκυρότητας blockchain");
            put("basicsAdd", "Προσθήκη");
            put("basicsCopiedQR", "Ο κώδικας QR αντιγράφηκε στο πρόχειρο.");
            put("basicsCopyQR", "Αντιγραφή κώδικα QR");
            put("basicsCurrentlyUnavailable", "προσωρινά μη διαθέσιμο");
            put("basicsDetails", "Λεπτομέρειες");
            put("basicsErrorDetails", "Λεπτομέρειες σφάλματος");
            put("basicsFormReset", "Εκκαθάριση");
            put("basicsHome", "Θάλασσα");
            put("basicsLangEl", "Ελληνικά");
            put("basicsLangEn", "English");
            put("basicsLogoTitle", "Λογότυπο");
            put("basicsSettings", "Ρυθμίσεις");
            put("basicsWelcomeUnderConstruction", "Η υπηρεσία βρίσκεται σε στάδιο ανάπτυξης.");
            put("blockchain", "Blockchain");
            put("blockchainBlockNumber", "Αριθμός μπλοκ");
            put("blockchainHash", "Τιμή κατατεμαχισμού");
            put("blockchainHashExpected", "Αναμενόμενη τιμή κατατεμαχισμού");
            put("blockchainHashFound", "Πραγματική τιμή κατατεμαχισμού");
            put("blockchainNumberTimestampOfFirst", "Αριθμός/Χρονοσφραγίδα πρώτου μπλοκ");
            put("blockchainNumberTimestampOfSecond", "Αριθμός/Χρονοσφραγίδα δεύτερου μπλοκ");
            put("blockchainSignatureInvalid", "Μη έγκυρη υπογραφή");
            put("blockchainSignatureValid", "Έγκυρη υπογραφή");
            put("blockchainTimestamp", "Χρονοσφραγίδα");
            put("companiesType", "Είδος δραστηριότητας");
            put("companiesTypeTankerManagementServices", "Υπηρεσίες διαχείρισης δεξαμενόπλοιων");
            put("company", "Εταιρεία");
            put("errorBlockchainNotValidated", "Κάτι συνέβη και δεν ήταν δυνατός ο έλεγχος εγκυρότητας του blockchain της υπηρεσίας.");
            put("errorChangeLanguageFailed", "Κάτι συνέβη και δεν ήταν δυνατή η αλλαγή γλώσσας.");
            put("errorChangePageTitleFailed", "Κάτι συνέβη και δεν ήταν δυνατή η αλλαγή του τίτλου της σελίδας.");
            put("errorChangesNotSaved", "Για κάποιο λόγο οι αλλαγές δεν αποθηκεύτηκαν.");
            put("errorCode", "Κωδικός σφάλματος:");
            put("errorContractNotFetched", "Κάτι συνέβη και δεν ήταν δυνατή η ανάκτηση της σύμβασης.");
            put("errorContractsNotFetched", "Κάτι συνέβη και δεν ήταν δυνατή η ανάκτηση των αποθηκευμένων συμβάσεων.");
            put("errorEmailAlreadyInUse", "Αυτή η διεύθυνση ηλεκτρονικού ταχυδρομείου χρησιμοποιείται ήδη.");
            put("errorEmailInvalid", "Η διεύθυνση ηλεκτρονικού ταχυδρομείου δεν είναι έγκυρη.");
            put("errorEmailNotChecked", "Κάτι συνέβη και δεν ήταν δυνατός ο έλεγχος της διεύθυνσης ηλεκτρονικού ταχυδρομείου.");
            put("errorInputNotNumerical", "Το πεδίο πρέπει να είναι αριθμητικό.");
            put("errorInputNotLetters", "Το πεδίο πρέπει να περιέχει γράμματα.");
            put("errorKeysNotGenerated", "Κάτι συνέβη και δεν ήταν δυνατή η δημιουργία των κλειδιών χρήστη.");
            put("errorLoginFailed", "Κάτι συνέβη και δεν ήταν δυνατή η είσοδος.");
            put("errorLoginFormNotValidated", "Κάτι συνέβη και δεν ήταν δυνατός ο έλεγχος της φόρμας εισόδου.");
            put("errorLogoutFailed", "Κάτι συνέβη και δεν ήταν δυνατή η έξοδος.");
            put("errorMaxFirstName", "Το όνομα πρέπει να περιέχει έως 100 χαρακτήρες.");
            put("errorMaxLastName", "Το επώνυμο πρέπει να περιέχει έως 100 χαρακτήρες.");
            put("errorMaxRegistryNumber", "Ο αριθμός μητρώου πρέπει να περιέχει έως 30 χαρακτήρες.");
            put("errorMaxVesselDwt", "Η χωρητικότητα εκτοπίσματος του πλοίου πρέπει να περιέχει έως 10 χαρακτήρες.");
            put("errorMaxVesselImoNumber", "Ο αριθμός IMO του πλοίου πρέπει να περιέχει έως 100 χαρακτήρες.");
            put("errorMaxVesselName", "Το όνομα του πλοίου πρέπει να περιέχει έως 100 χαρακτήρες.");
            put("errorMessage", "Μήνυμα σφάλματος:");
            put("errorNoUserWithSuchCredentials", "Δεν υπάρχει λογαριασμός με αυτά τα στοιχεία.");
            put("errorPrivateKeyInvalid", "Το ιδιωτικό κλειδί που εισαγάγατε δεν είναι έγκυρο.");
            put("errorRegisterFailed", "Κάτι συνέβη και δεν ήταν δυνατή η ολοκλήρωση της εγγραφής.");
            put("errorRegisterFormNotValidated", "Κάτι συνέβη και δεν ήταν δυνατός ο έλεγχος της φόρμας εγγραφής.");
            put("errorRequiredAddress", "Το πεδίο της διεύθυνσης είναι υποχρεωτικό.");
            put("errorRequiredCompanyName", "Το πεδίο του ονόματος της εταιρείας είναι υποχρεωτικό.");
            put("errorRequiredCompanyType", "Το πεδίο του είδους δραστηριότητας είναι υποχρεωτικό.");
            put("errorRequiredEmail", "Το πεδίο της διεύθυνσης ηλεκτρονικού ταχυδρομείου είναι υποχρεωτικό.");
            put("errorRequiredFirstName", "Το πεδίο του ονόματος είναι υποχρεωτικό.");
            put("errorRequiredLastName", "Το πεδίο του επωνύμου είναι υποχρεωτικό.");
            put("errorRequiredPosition", "Πρέπει να επιλέξετε την ιδιότητά σας.");
            put("errorRequiredPrivateKey", "Πρέπει να εισαγάγετε το ιδιωτικό κλειδί σας για να εισέλθετε.");
            put("errorRequiredRegistryNumber", "Το πεδίο του αριθμού μητρώου είναι υποχρεωτικό.");
            put("errorRequiredVesselDwt", "Το πεδίο της χωρητικότητας εκτοπίσματος του πλοίου είναι υποχρεωτικό.");
            put("errorRequiredVesselFlag", "Το πεδίο της σημαίας του πλοίου είναι υποχρεωτικό.");
            put("errorRequiredVesselImoNumber", "Το πεδίο του αριθμού IMO του πλοίου είναι υποχρεωτικό.");
            put("errorRequiredVesselName", "Το πεδίο του ονόματος του πλοίου είναι υποχρεωτικό.");
            put("errorRequiredVesselYearBuilt", "Το πεδίο του έτους κατασκευής του πλοίου είναι υποχρεωτικό.");
            put("errorSizeVesselFlag", "Η σημαία του πλοίου πρέπει να περιέχει 2 χαρακτήρες.");
            put("errorSizeVesselYearBuilt", "Το έτος κατασκευής του πλοίου πρέπει να είναι τετραψήφιο.");
            put("errorSubmittedNotSaved", "Τα στοιχεία υποβλήθηκαν επιτυχώς αλλά για κάποιο λόγο δεν αποθηκεύτηκαν.");
            put("errorVesselNotAdded", "Κάτι συνέβη και δεν ήταν δυνατή η προσθήκη του πλοίου.");
            put("errorVesselNotUpdated", "Κάτι συνέβη και δεν ήταν δυνατή η ενημέρωση των στοιχείων του πλοίου.");
            put("errorVesselUpdatedButVesselsRegistryNotFetched", "Τα στοιχεία του πλοίου ενημερώθηκαν επιτυχώς αλλά δεν ήταν δυνατή η φόρτωση του μητρώου πλοίων.");
            put("errorVesselsRegistryNotFetched", "Κάτι συνέβη και δεν ήταν δυνατή η φόρτωση του μητρώου πλοίων.");
            put("hintEdit", "Για να πραγματοποιήσετε αλλαγές, επιλέξτε το πεδίο που θέλετε να τροποποιήσετε, επεξεργαστείτε το και κάντε κλικ έξω από αυτό.");
            put("legalContractingParties", "Συμβαλλομενα Μερη");
            put("legalContracts", "Συμβάσεις");
            put("legalContractsAllContracts", "Όλες οι συμβάσεις");
            put("legalContractsClauses", "Ρητρες");
            put("legalContractsEmpty", "Δεν έχετε συμβάσεις στο αρχείο σας.");
            put("legalContractsEssentials", "Ουσιωδη Στοιχεια");
            put("legalContractsNewContract", "Σύνταξη νέας σύμβασης");
            put("legalContractsOnBehalfOf", "στο όνομα και για λογαριασμό του");
            put("legalContractsReadable", "Αναγνώσιμη μορφή");
            put("legalContractsTitle", "Τίτλος");
            put("legalContractsTitlesLowertimeCharter", "Χρονοναύλωση");
            put("legalContractsTitlesUppertimeCharter", "Χρονοναυλωση");
            put("legalContractsToggleLegen", "Εμφάνιση/Απόκρυψη ρήτρας Legen");
            put("legalEnableClause", "Ενεργοποίηση ρήτρας");
            put("otherSectionUnderConstruction", "Αυτή η ενότητα βρίσκεται σε στάδιο ανάπτυξης…");
            put("settingsAbout", "Πληροφορίες");
            put("settingsAppearance", "Εμφάνιση");
            put("settingsChangeLanguage", "Αλλαγή γλώσσας");
            put("settingsDark", "Σκούρο");
            put("settingsLanguage", "Γλώσσα");
            put("settingsLight", "Φωτεινό");
            put("settingsTheme", "Θέμα");
            put("usersCopyKeysToClipboard", "Αντιγραφή κλειδιών στο πρόχειρο");
            put("usersEmail", "Διεύθυνση ηλεκτρονικού ταχυδρομείου");
            put("usersGeneratingKeysMessage", "Δημιουργία κλειδιών…");
            put("usersFirstName", "Όνομα");
            put("usersHome", "Αρχική");
            put("usersInvalidFirstName", "Το όνομα που εισαγάγατε δεν είναι έγκυρο.");
            put("usersInvalidLastName", "Το επώνυμο που εισαγάγατε δεν είναι έγκυρο.");
            put("usersKeysCopiedToClipboard", "Τα κλειδιά αντιγράφηκαν στο πρόχειρο.");
            put("usersLastName", "Επώνυμο");
            put("usersLogin", "Είσοδος");
            put("usersLoginWithQRScan", "Σαρώστε το ιδιωτικό κλειδί σας:");
            put("usersLogout", "Έξοδος");
            put("usersLogoutSuccess", "Έχετε αποσυνδεθεί επιτυχώς. Καλή ξεκούραση!");
            put("usersMessageBeforeRegister", "Πατώντας το κουμπί «Εγγραφή» παρακάτω συμφωνείτε ότι έχετε προβεί σε αντιγραφή (πατώντας πάνω σε οποιονδήποτε κωδικό QR ανωτέρω) και ασφαλή αποθήκευση του δημόσιου και του ιδιωτικού κλειδιού σας και ότι φέρετε την αποκλειστική ευθύνη σε περίπτωση απώλειάς τους.");
            put("usersOrTypeQRCodeLogin", "Ή εισαγάγετέ το εδώ:");
            put("usersPosition", "Ιδιότητα");
            put("usersPositionscompanyVesselsRegistryManager", "Διαχειριστής μητρώου πλοίων");
            put("usersPositionslegalEngineer", "Νομικός μηχανικός");
            put("usersPrivateKey", "Ιδιωτικό κλειδί");
            put("usersPublicKey", "Δημόσιο κλειδί");
            put("usersRegister", "Εγγραφή");
            put("usersRevealPrivateKey", "Εμφάνιση ιδιωτικού κλειδιού");
            put("usersSwitchToLogin", "Εναλλαγή σε Είσοδο");
            put("usersSwitchToRegister", "Εναλλαγή σε Εγγραφή");
            put("usersWelcome", "Καλώς ορίσατε");
            put("usersWelcomeSubtitle", "Χρησιμοποιήστε τη γραμμή περιήγησης για περισσότερα.");
            put("vesselsAddNew", "Προσθήκη πλοίου");
            put("vesselsRegistry", "Μητρώο πλοίων");
            put("vesselsDwt", "Χωρ. εκτοπίσματος (DWT)");
            put("vesselsFlag", "Σημαία");
            put("vesselsFlagsGR", "GR - Ελλάδα");
            put("vesselsFlagsUS", "US - Ηνωμένες Πολιτείες");
            put("vesselsImoNumber", "Αριθμός IMO");
            put("vesselsInvalidImoNumber", "Ο αριθμός IMO που εισαγάγατε δεν είναι έγκυρος.");
            put("vesselsInvalidName", "Το όνομα του πλοίου που εισαγάγατε δεν είναι έγκυρο.");
            put("vesselsName", "Όνομα");
            put("vesselsRegistryIsEmpty", "Δεν έχετε προσθέσει πλοία στο μητρώο ακόμα.");
            put("vesselsUnderConstruction", "Υπό ναυπήγηση");
            put("vesselsVesselSuccessfullyAdded", "Το πλοίο προστέθηκε με επιτυχία.");
            put("vesselsYearBuilt", "Έτος κατασκευής");
        }});
        put("en", new HashMap<>() {{
            put("aboutAttention", "ATTENTION: THIS PROJECT IS UNDER DEVELOPMENT. UNTIL IT IS HAS REACHED THE FINAL RELEASE STAGE, NO LIABILITY ARISES IN CASE OF ANY MALFUNCTION, LOSS OF DATA OR ANY OTHER NEGATIVE CONSEQUENCES CAUSED BY ITS USE.");
            put("aboutExperimental", "“Thalassa” is an experimental web service for the marine industry based on blockchain technology. See <a href=\"https://github.com/jdouv/Thalassa\" target=\"_blank\">here</a> for more information.");
            put("aboutSubtitle", "Electronic service for the marine industry.");
            put("adminBlockchainIsEmpty", "The service’s blockchain is empty, therefore there is no need for validation.");
            put("adminBlockchainIsInvalid", "For some reason, the service’s blockchain is not valid.");
            put("adminBlockchainIsValid", "The service’s blockchain is valid.");
            put("adminBlockchainResultsCalculationMessage", "In the following blocks, the hash expected is different from the hash found.");
            put("adminBlockchainResultsReferenceMessage", "In the following blocks, the second block’s reference to the first block’s hash is different from the first block’s actual hash.");
            put("adminValidateBlockchain", "Validate blockchain");
            put("basicsAdd", "Add");
            put("basicsCopiedQR", "The QR code has been copied to the clipboard.");
            put("basicsCopyQR", "Copy QR code");
            put("basicsCurrentlyUnavailable", "currently unavailable");
            put("basicsDetails", "Details");
            put("basicsErrorDetails", "Error details");
            put("basicsFormReset", "Reset");
            put("basicsHome", "Thalassa");
            put("basicsLangEl", "Ελληνικά");
            put("basicsLangEn", "English");
            put("basicsLogoTitle", "Logo");
            put("basicsSettings", "Settings");
            put("basicsWelcomeUnderConstruction", "This project is under development.");
            put("blockchain", "Blockchain");
            put("blockchainBlockNumber", "Block number");
            put("blockchainHash", "Hash");
            put("blockchainHashExpected", "Expected hash");
            put("blockchainHashFound", "Hash found");
            put("blockchainNumberTimestampOfFirst", "Number/Timestamp of first block");
            put("blockchainNumberTimestampOfSecond", "Number/Timestamp of second block");
            put("blockchainSignatureInvalid", "Invalid signature");
            put("blockchainSignatureValid", "Valid signature");
            put("blockchainTimestamp", "Timestamp");
            put("companiesType", "Type of activity");
            put("companiesTypeTankerManagementServices", "Tanker management services");
            put("company", "Company");
            put("errorBlockchainNotValidated", "Something happened and the service’s blockchain could not be validated.");
            put("errorChangeLanguageFailed", "Something happened and the language could not be changed.");
            put("errorChangePageTitleFailed", "Something happened and the page title could not be changed.");
            put("errorChangesNotSaved", "For some reason the changes were not saved.");
            put("errorCode", "Error status:");
            put("errorContractNotFetched", "Something happened and the contract could not be fetched.");
            put("errorContractsNotFetched", "Something happened and the saved contracts could not be fetched.");
            put("errorEmailAlreadyInUse", "This e-mail is already in use.");
            put("errorEmailInvalid", "This e-mail is not valid.");
            put("errorEmailNotChecked", "Something happened and the e-mail could not be checked.");
            put("errorInputNotNumerical", "The input must be numerical.");
            put("errorInputNotLetters", "The input must contain letters.");
            put("errorKeysNotGenerated", "Something happened and user keys generation failed.");
            put("errorLoginFailed", "Something happened and login failed.");
            put("errorLoginFormNotValidated", "Something happened and the login form could not be validated.");
            put("errorLogoutFailed", "Something happened and you did not logout successfully.");
            put("errorMaxFirstName", "The first name must contain at most 100 characters.");
            put("errorMaxLastName", "The last name must contain at most 100 characters.");
            put("errorMaxRegistryNumber", "The registry number must contain at most 100 characters.");
            put("errorMaxVesselDwt", "The vessel’s deadweight tonnage must contain at most 10 characters.");
            put("errorMaxVesselImoNumber", "The vessel’s IMO number must contain at most 100 characters.");
            put("errorMaxVesselName", "The vessel’s name must contain at most 100 characters.");
            put("errorMessage", "Error message:");
            put("errorNoUserWithSuchCredentials", "There is no account with such credentials.");
            put("errorPrivateKeyInvalid", "The private key is invalid.");
            put("errorRegisterFailed", "Something happened and register failed.");
            put("errorRegisterFormNotValidated", "Something happened and the register form could not be validated.");
            put("errorRequiredAddress", "The address field is required.");
            put("errorRequiredCompanyName", "The company name field is required.");
            put("errorRequiredCompanyType", "The type of activity field is required.");
            put("errorRequiredEmail", "The e-mail field is required.");
            put("errorRequiredFirstName", "The first name field is required.");
            put("errorRequiredLastName", "The last name field is required.");
            put("errorRequiredPosition", "You must select your position.");
            put("errorRequiredPrivateKey", "You must enter your private key to login.");
            put("errorRequiredRegistryNumber", "The registry number field is required.");
            put("errorRequiredVesselDwt", "The vessel’s deadweight tonnage is required.");
            put("errorRequiredVesselFlag", "The vessel’s flag is required.");
            put("errorRequiredVesselImoNumber", "The vessel’s IMO number is required.");
            put("errorRequiredVesselName", "The vessel’s name is required.");
            put("errorRequiredVesselYearBuilt", "The year when the vessel was built is required.");
            put("errorSizeVesselFlag", "The vessel’s flag must contain 2 characters.");
            put("errorSizeVesselYearBuilt", "The year when the vessel was built must contain 4 characters.");
            put("errorSubmittedNotSaved", "The data was successfully submitted but for some reason it was not saved.");
            put("errorVesselNotAdded", "Something happened and the vessel could not be added.");
            put("errorVesselNotUpdated", "Something happened and the vessel’s data could not be updated.");
            put("errorVesselUpdatedButVesselsRegistryNotFetched", "The vessel’s data could was successfully updated but the vessels registry could not be fetched.");
            put("errorVesselsRegistryNotFetched", "Something happened and the vessels registry could not be fetched.");
            put("hintEdit", "To make changes, select the desired field, edit it and click outside.");
            put("legalContractingParties", "Contracting Parties");
            put("legalContracts", "Contracts");
            put("legalContractsAllContracts", "All contracts");
            put("legalContractsClauses", "Clauses");
            put("legalContractsEmpty", "You do not have any contracts in your file.");
            put("legalContractsEssentials", "Essential Elements");
            put("legalContractsToggleLegen", "Show/Hide Legen clause");
            put("legalContractsNewContract", "Draft new contract");
            put("legalContractsOnBehalfOf", "on behalf of");
            put("legalContractsReadable", "Readable");
            put("legalContractsTitle", "Title");
            put("legalContractsTitlesLowertimeCharter", "Time Charter");
            put("legalContractsTitlesUppertimeCharter", "Time Charter");
            put("legalEnableClause", "Enable clause");
            put("otherSectionUnderConstruction", "This section is under construction…");
            put("settingsAbout", "About");
            put("settingsAppearance", "Appearance");
            put("settingsChangeLanguage", "Change language");
            put("settingsDark", "Dark");
            put("settingsLanguage", "Language");
            put("settingsLight", "Light");
            put("settingsTheme", "Theme");
            put("usersCopyKeysToClipboard", "Copy keys to clipboard");
            put("usersEmail", "E-mail");
            put("usersFirstName", "First name");
            put("usersGeneratingKeysMessage", "Generating keys…");
            put("usersHome", "Home");
            put("usersInvalidFirstName", "The first name is invalid.");
            put("usersInvalidLastName", "The last name is invalid.");
            put("usersKeysCopiedToClipboard", "The keys have been copied to the clipboard.");
            put("usersLastName", "Last name");
            put("usersLogin", "Login");
            put("usersLoginWithQRScan", "Scan your QR private key:");
            put("usersLogout", "Logout");
            put("usersLogoutSuccess", "You have logged out successfully. Rest up!");
            put("usersMessageBeforeRegister", "By pressing “Submit” below you agree that you have copied (by tapping any of the QR codes above) and safely saved your public and private keys and that you are solely responsible in case of their loss.");
            put("usersOrTypeQRCodeLogin", "Or type it here:");
            put("usersPosition", "Position");
            put("usersPositionscompanyVesselsRegistryManager", "Vessels registry manager");
            put("usersPositionslegalEngineer", "Legal engineer");
            put("usersPrivateKey", "Private key");
            put("usersPublicKey", "Public key");
            put("usersRegister", "Register");
            put("usersRevealPrivateKey", "Reveal private key");
            put("usersSwitchToLogin", "Switch to Login");
            put("usersSwitchToRegister", "Switch to Register");
            put("usersWelcome", "Welcome");
            put("usersWelcomeSubtitle", "Use navigation bar for more.");
            put("vesselsAddNew", "Add vessel");
            put("vesselsRegistry", "Vessels registry");
            put("vesselsDwt", "DWT");
            put("vesselsFlag", "Flag");
            put("vesselsFlagsGR", "GR - Greece");
            put("vesselsFlagsUS", "US - United States");
            put("vesselsImoNumber", "IMO number");
            put("vesselsInvalidImoNumber", "The IMO number is invalid.");
            put("vesselsInvalidName", "The vessel name is invalid.");
            put("vesselsName", "Name");
            put("vesselsRegistryIsEmpty", "You have not added vessels to the registry yet.");
            put("vesselsUnderConstruction", "Under construction");
            put("vesselsVesselSuccessfullyAdded", "The vessel has been added successfully.");
            put("vesselsYearBuilt", "Year built");
        }});
    }};
}