//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thalassa.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: THIS PROJECT IS UNDER DEVELOPMENT. UNTIL IT IS HAS REACHED THE FINAL RELEASE STAGE, NO LIABILITY ARISES IN CASE OF ANY MALFUNCTION, LOSS OF DATA OR ANY OTHER NEGATIVE CONSEQUENCES CAUSED BY ITS USE..
        /// </summary>
        public static string About_Attention {
            get {
                return ResourceManager.GetString("About.Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Thalassa” is an experimental web service for the marine industry based on blockchain technology. See &lt;a href=&quot;https://github.com/jdouv/Thalassa&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt; for more information..
        /// </summary>
        public static string About_Experimental {
            get {
                return ResourceManager.GetString("About.Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic service for the marine industry..
        /// </summary>
        public static string About_Subtitle {
            get {
                return ResourceManager.GetString("About.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidity is reported in the following blocks:.
        /// </summary>
        public static string Admin_BlockchainInvalidResults {
            get {
                return ResourceManager.GetString("Admin.BlockchainInvalidResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service’s blockchain is empty, therefore there is no need for validation..
        /// </summary>
        public static string Admin_BlockchainIsEmpty {
            get {
                return ResourceManager.GetString("Admin.BlockchainIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, the service’s blockchain is not valid..
        /// </summary>
        public static string Admin_BlockchainIsInvalid {
            get {
                return ResourceManager.GetString("Admin.BlockchainIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service’s blockchain is valid..
        /// </summary>
        public static string Admin_BlockchainIsValid {
            get {
                return ResourceManager.GetString("Admin.BlockchainIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the following blocks, the hash expected is different from the hash found..
        /// </summary>
        public static string Admin_BlockchainResultsCalculationMessage {
            get {
                return ResourceManager.GetString("Admin.BlockchainResultsCalculationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the following blocks, the second block’s reference to the first block’s hash is different from the first block’s actual hash..
        /// </summary>
        public static string Admin_BlockchainResultsReferenceMessage {
            get {
                return ResourceManager.GetString("Admin.BlockchainResultsReferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate blockchain.
        /// </summary>
        public static string Admin_ValidateBlockchain {
            get {
                return ResourceManager.GetString("Admin.ValidateBlockchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QR code has been copied to the clipboard..
        /// </summary>
        public static string Basics_CopiedQR {
            get {
                return ResourceManager.GetString("Basics.CopiedQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy QR code.
        /// </summary>
        public static string Basics_CopyQR {
            get {
                return ResourceManager.GetString("Basics.CopyQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currently unavailable.
        /// </summary>
        public static string Basics_CurrentlyUnavailable {
            get {
                return ResourceManager.GetString("Basics.CurrentlyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Basics_Details {
            get {
                return ResourceManager.GetString("Basics.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        public static string Basics_ErrorDetails {
            get {
                return ResourceManager.GetString("Basics.ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Basics_Eye {
            get {
                return ResourceManager.GetString("Basics.Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Basics_FormReset {
            get {
                return ResourceManager.GetString("Basics.FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thalassa.
        /// </summary>
        public static string Basics_Home {
            get {
                return ResourceManager.GetString("Basics.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελληνικά.
        /// </summary>
        public static string Basics_Lang_El {
            get {
                return ResourceManager.GetString("Basics.Lang.El", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Basics_Lang_En {
            get {
                return ResourceManager.GetString("Basics.Lang.En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Basics_Logo_Title {
            get {
                return ResourceManager.GetString("Basics.Logo.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Basics_Settings {
            get {
                return ResourceManager.GetString("Basics.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is under development..
        /// </summary>
        public static string Basics_WelcomeUnderConstruction {
            get {
                return ResourceManager.GetString("Basics.WelcomeUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block number.
        /// </summary>
        public static string Blockchain_BlockNumber {
            get {
                return ResourceManager.GetString("Blockchain.BlockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        public static string Blockchain_Hash {
            get {
                return ResourceManager.GetString("Blockchain.Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hash.
        /// </summary>
        public static string Blockchain_HashExpected {
            get {
                return ResourceManager.GetString("Blockchain.HashExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash found.
        /// </summary>
        public static string Blockchain_HashFound {
            get {
                return ResourceManager.GetString("Blockchain.HashFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/Timestamp of first block.
        /// </summary>
        public static string Blockchain_NumberTimestampOfFirst {
            get {
                return ResourceManager.GetString("Blockchain.NumberTimestampOfFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/Timestamp of second block.
        /// </summary>
        public static string Blockchain_NumberTimestampOfSecond {
            get {
                return ResourceManager.GetString("Blockchain.NumberTimestampOfSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature.
        /// </summary>
        public static string Blockchain_SignatureInvalid {
            get {
                return ResourceManager.GetString("Blockchain.SignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid signature.
        /// </summary>
        public static string Blockchain_SignatureValid {
            get {
                return ResourceManager.GetString("Blockchain.SignatureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Blockchain_Timestamp {
            get {
                return ResourceManager.GetString("Blockchain.Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the service’s blockchain could not be validated..
        /// </summary>
        public static string Error_BlockchainNotValidated {
            get {
                return ResourceManager.GetString("Error.BlockchainNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error status:.
        /// </summary>
        public static string Error_Code {
            get {
                return ResourceManager.GetString("Error.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the contract could not be fetched..
        /// </summary>
        public static string Error_ContractNotFetched {
            get {
                return ResourceManager.GetString("Error.ContractNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the saved contracts could not be fetched..
        /// </summary>
        public static string Error_ContractsNotFetched {
            get {
                return ResourceManager.GetString("Error.ContractsNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already in use..
        /// </summary>
        public static string Error_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Error.EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is not valid..
        /// </summary>
        public static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error.EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the e-mail could not be checked..
        /// </summary>
        public static string Error_EmailNotChecked {
            get {
                return ResourceManager.GetString("Error.EmailNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and user keys generation failed..
        /// </summary>
        public static string Error_KeysNotGenerated {
            get {
                return ResourceManager.GetString("Error.KeysNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and login failed..
        /// </summary>
        public static string Error_LoginFailed {
            get {
                return ResourceManager.GetString("Error.LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the login form could not be validated..
        /// </summary>
        public static string Error_LoginFormNotValidated {
            get {
                return ResourceManager.GetString("Error.LoginFormNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the login page could not be fetched..
        /// </summary>
        public static string Error_LoginPageNotFetched {
            get {
                return ResourceManager.GetString("Error.LoginPageNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxFirstName {
            get {
                return ResourceManager.GetString("Error.MaxFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxLastName {
            get {
                return ResourceManager.GetString("Error.MaxLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s deadweight tonnage must contain at most 10 characters..
        /// </summary>
        public static string Error_MaxVesselDwt {
            get {
                return ResourceManager.GetString("Error.MaxVesselDwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s IMO number must contain at most 10 characters..
        /// </summary>
        public static string Error_MaxVesselImoNumber {
            get {
                return ResourceManager.GetString("Error.MaxVesselImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxVesselName {
            get {
                return ResourceManager.GetString("Error.MaxVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the navigation bar could not be loaded..
        /// </summary>
        public static string Error_NavbarLoadingFailed {
            get {
                return ResourceManager.GetString("Error.NavbarLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account with such credentials..
        /// </summary>
        public static string Error_NoUserWithSuchCredentials {
            get {
                return ResourceManager.GetString("Error.NoUserWithSuchCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is invalid..
        /// </summary>
        public static string Error_PrivateKeyInvalid {
            get {
                return ResourceManager.GetString("Error.PrivateKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and register failed..
        /// </summary>
        public static string Error_RegisterFailed {
            get {
                return ResourceManager.GetString("Error.RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the register form could not be validated..
        /// </summary>
        public static string Error_RegisterFormNotValidated {
            get {
                return ResourceManager.GetString("Error.RegisterFormNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the register page could not be fetched..
        /// </summary>
        public static string Error_RegisterPageNotFetched {
            get {
                return ResourceManager.GetString("Error.RegisterPageNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail field is required..
        /// </summary>
        public static string Error_RequiredEmail {
            get {
                return ResourceManager.GetString("Error.RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field is required..
        /// </summary>
        public static string Error_RequiredFirstName {
            get {
                return ResourceManager.GetString("Error.RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field is required..
        /// </summary>
        public static string Error_RequiredLastName {
            get {
                return ResourceManager.GetString("Error.RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select your position..
        /// </summary>
        public static string Error_RequiredPosition {
            get {
                return ResourceManager.GetString("Error.RequiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your private key to login..
        /// </summary>
        public static string Error_RequiredPrivateKey {
            get {
                return ResourceManager.GetString("Error.RequiredPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s deadweight tonnage is required..
        /// </summary>
        public static string Error_RequiredVesselDwt {
            get {
                return ResourceManager.GetString("Error.RequiredVesselDwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s flag is required..
        /// </summary>
        public static string Error_RequiredVesselFlag {
            get {
                return ResourceManager.GetString("Error.RequiredVesselFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s IMO number is required..
        /// </summary>
        public static string Error_RequiredVesselImoNumber {
            get {
                return ResourceManager.GetString("Error.RequiredVesselImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s name is required..
        /// </summary>
        public static string Error_RequiredVesselName {
            get {
                return ResourceManager.GetString("Error.RequiredVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year when the vessel was built is required..
        /// </summary>
        public static string Error_RequiredVesselYearBuilt {
            get {
                return ResourceManager.GetString("Error.RequiredVesselYearBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s flag must contain 2 characters..
        /// </summary>
        public static string Error_SizeVesselFlag {
            get {
                return ResourceManager.GetString("Error.SizeVesselFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year when the vessel was built must contain 4 characters..
        /// </summary>
        public static string Error_SizeVesselYearBuilt {
            get {
                return ResourceManager.GetString("Error.SizeVesselYearBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and the welcome page could not be fetched..
        /// </summary>
        public static string Error_WelcomePageNotFetched {
            get {
                return ResourceManager.GetString("Error.WelcomePageNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracting Parties.
        /// </summary>
        public static string Legal_ContractingParties {
            get {
                return ResourceManager.GetString("Legal.ContractingParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Legal_Contracts {
            get {
                return ResourceManager.GetString("Legal.Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contracts.
        /// </summary>
        public static string Legal_Contracts_AllContracts {
            get {
                return ResourceManager.GetString("Legal.Contracts.AllContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clauses.
        /// </summary>
        public static string Legal_Contracts_Clauses {
            get {
                return ResourceManager.GetString("Legal.Contracts.Clauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any contracts in your file..
        /// </summary>
        public static string Legal_Contracts_Empty {
            get {
                return ResourceManager.GetString("Legal.Contracts.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential Elements.
        /// </summary>
        public static string Legal_Contracts_Essentials {
            get {
                return ResourceManager.GetString("Legal.Contracts.Essentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft new contract.
        /// </summary>
        public static string Legal_Contracts_NewContract {
            get {
                return ResourceManager.GetString("Legal.Contracts.NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on behalf of.
        /// </summary>
        public static string Legal_Contracts_OnBehalfOf {
            get {
                return ResourceManager.GetString("Legal.Contracts.OnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readable.
        /// </summary>
        public static string Legal_Contracts_Readable {
            get {
                return ResourceManager.GetString("Legal.Contracts.Readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Legal_Contracts_Title {
            get {
                return ResourceManager.GetString("Legal.Contracts.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Charter.
        /// </summary>
        public static string Legal_Contracts_Titles_Lower_TimeCharter {
            get {
                return ResourceManager.GetString("Legal.Contracts.Titles.Lower.TimeCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Charter.
        /// </summary>
        public static string Legal_Contracts_Titles_Upper_TimeCharter {
            get {
                return ResourceManager.GetString("Legal.Contracts.Titles.Upper.TimeCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Legen clause.
        /// </summary>
        public static string Legal_Contracts_ToggleLegen {
            get {
                return ResourceManager.GetString("Legal.Contracts.ToggleLegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable clause.
        /// </summary>
        public static string Legal_EnableClause {
            get {
                return ResourceManager.GetString("Legal.EnableClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is under construction….
        /// </summary>
        public static string Other_SectionUnderConstruction {
            get {
                return ResourceManager.GetString("Other.SectionUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings.Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string Settings_ChangeLanguage {
            get {
                return ResourceManager.GetString("Settings.ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Dark {
            get {
                return ResourceManager.GetString("Settings.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect after you reload the page..
        /// </summary>
        public static string Settings_EffectAfterRestart {
            get {
                return ResourceManager.GetString("Settings.EffectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Light {
            get {
                return ResourceManager.GetString("Settings.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy keys to clipboard.
        /// </summary>
        public static string Users_CopyKeysToClipboard {
            get {
                return ResourceManager.GetString("Users.CopyKeysToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Users_Email {
            get {
                return ResourceManager.GetString("Users.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Users_FirstName {
            get {
                return ResourceManager.GetString("Users.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Users_Home {
            get {
                return ResourceManager.GetString("Users.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is invalid..
        /// </summary>
        public static string Users_InvalidFirstName {
            get {
                return ResourceManager.GetString("Users.InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is invalid..
        /// </summary>
        public static string Users_InvalidLastName {
            get {
                return ResourceManager.GetString("Users.InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keys have been copied to the clipboard..
        /// </summary>
        public static string Users_KeysCopiedToClipboard {
            get {
                return ResourceManager.GetString("Users.KeysCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Users_LastName {
            get {
                return ResourceManager.GetString("Users.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Users_Login {
            get {
                return ResourceManager.GetString("Users.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your QR private key:.
        /// </summary>
        public static string Users_LoginWithQRScan {
            get {
                return ResourceManager.GetString("Users.LoginWithQRScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Users_Logout {
            get {
                return ResourceManager.GetString("Users.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By pressing “Submit” below you agree that you have copied (by tapping any of the QR codes above) and safely saved your public and private keys and that you are solely responsible in case of their loss..
        /// </summary>
        public static string Users_MessageBeforeRegister {
            get {
                return ResourceManager.GetString("Users.MessageBeforeRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or type it here:.
        /// </summary>
        public static string Users_OrTypeQRCodeLogin {
            get {
                return ResourceManager.GetString("Users.OrTypeQRCodeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Users_Position {
            get {
                return ResourceManager.GetString("Users.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal engineer.
        /// </summary>
        public static string Users_Positions_LegalEngineer {
            get {
                return ResourceManager.GetString("Users.Positions.LegalEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipbroker.
        /// </summary>
        public static string Users_Positions_Shipbroker {
            get {
                return ResourceManager.GetString("Users.Positions.Shipbroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        public static string Users_PrivateKey {
            get {
                return ResourceManager.GetString("Users.PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        public static string Users_PublicKey {
            get {
                return ResourceManager.GetString("Users.PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Users_Register {
            get {
                return ResourceManager.GetString("Users.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal private key.
        /// </summary>
        public static string Users_RevealPrivateKey {
            get {
                return ResourceManager.GetString("Users.RevealPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Login.
        /// </summary>
        public static string Users_SwitchToLogin {
            get {
                return ResourceManager.GetString("Users.SwitchToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Register.
        /// </summary>
        public static string Users_SwitchToRegister {
            get {
                return ResourceManager.GetString("Users.SwitchToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Users_Welcome {
            get {
                return ResourceManager.GetString("Users.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use navigation bar for more..
        /// </summary>
        public static string Users_WelcomeSubtitle {
            get {
                return ResourceManager.GetString("Users.WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWT.
        /// </summary>
        public static string Vessels_Dwt {
            get {
                return ResourceManager.GetString("Vessels.Dwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Vessels_Flag {
            get {
                return ResourceManager.GetString("Vessels.Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMO number.
        /// </summary>
        public static string Vessels_ImoNumber {
            get {
                return ResourceManager.GetString("Vessels.ImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Vessels_Name {
            get {
                return ResourceManager.GetString("Vessels.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year built.
        /// </summary>
        public static string Vessels_YearBuilt {
            get {
                return ResourceManager.GetString("Vessels.YearBuilt", resourceCulture);
            }
        }
    }
}
