//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thalassa.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already in use..
        /// </summary>
        public static string Error_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Error.EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is not valid..
        /// </summary>
        public static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error.EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxFirstName {
            get {
                return ResourceManager.GetString("Error.MaxFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxLastName {
            get {
                return ResourceManager.GetString("Error.MaxLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s deadweight tonnage must contain at most 10 characters..
        /// </summary>
        public static string Error_MaxVesselDwt {
            get {
                return ResourceManager.GetString("Error.MaxVesselDwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s IMO number must contain at most 10 characters..
        /// </summary>
        public static string Error_MaxVesselImoNumber {
            get {
                return ResourceManager.GetString("Error.MaxVesselImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s name must contain at most 30 characters..
        /// </summary>
        public static string Error_MaxVesselName {
            get {
                return ResourceManager.GetString("Error.MaxVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account with such credentials..
        /// </summary>
        public static string Error_NoUserWithSuchCredentials {
            get {
                return ResourceManager.GetString("Error.NoUserWithSuchCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is invalid..
        /// </summary>
        public static string Error_PrivateKeyInvalid {
            get {
                return ResourceManager.GetString("Error.PrivateKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail field is required..
        /// </summary>
        public static string Error_RequiredEmail {
            get {
                return ResourceManager.GetString("Error.RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field is required..
        /// </summary>
        public static string Error_RequiredFirstName {
            get {
                return ResourceManager.GetString("Error.RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field is required..
        /// </summary>
        public static string Error_RequiredLastName {
            get {
                return ResourceManager.GetString("Error.RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select your position..
        /// </summary>
        public static string Error_RequiredPosition {
            get {
                return ResourceManager.GetString("Error.RequiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your private key to login..
        /// </summary>
        public static string Error_RequiredPrivateKey {
            get {
                return ResourceManager.GetString("Error.RequiredPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s deadweight tonnage is required..
        /// </summary>
        public static string Error_RequiredVesselDwt {
            get {
                return ResourceManager.GetString("Error.RequiredVesselDwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s flag is required..
        /// </summary>
        public static string Error_RequiredVesselFlag {
            get {
                return ResourceManager.GetString("Error.RequiredVesselFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s IMO number is required..
        /// </summary>
        public static string Error_RequiredVesselImoNumber {
            get {
                return ResourceManager.GetString("Error.RequiredVesselImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s name is required..
        /// </summary>
        public static string Error_RequiredVesselName {
            get {
                return ResourceManager.GetString("Error.RequiredVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year when the vessel was built is required..
        /// </summary>
        public static string Error_RequiredVesselYearBuilt {
            get {
                return ResourceManager.GetString("Error.RequiredVesselYearBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vessel’s flag must contain 2 characters..
        /// </summary>
        public static string Error_SizeVesselFlag {
            get {
                return ResourceManager.GetString("Error.SizeVesselFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year when the vessel was built must contain 4 characters..
        /// </summary>
        public static string Error_SizeVesselYearBuilt {
            get {
                return ResourceManager.GetString("Error.SizeVesselYearBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Users_Email {
            get {
                return ResourceManager.GetString("Users.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Users_FirstName {
            get {
                return ResourceManager.GetString("Users.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Users_LastName {
            get {
                return ResourceManager.GetString("Users.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Users_Position {
            get {
                return ResourceManager.GetString("Users.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        public static string Users_PrivateKey {
            get {
                return ResourceManager.GetString("Users.PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWT.
        /// </summary>
        public static string Vessels_Dwt {
            get {
                return ResourceManager.GetString("Vessels.Dwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Vessels_Flag {
            get {
                return ResourceManager.GetString("Vessels.Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Vessels_Name {
            get {
                return ResourceManager.GetString("Vessels.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year built.
        /// </summary>
        public static string Vessels_YearBuilt {
            get {
                return ResourceManager.GetString("Vessels.YearBuilt", resourceCulture);
            }
        }
    }
}
